{:user {:plugins [#_[venantius/ultra "0.6.0"]
                  [lein-ancient "0.6.15"]
                  [lein-auto "0.1.3"]
                  [lein-kibit "0.1.8"]
                  [lein-nvd "1.3.0"]
                  [venantius/yagni "0.1.7"]
                  [jonase/eastwood "0.3.7"]
                  [lein-cloverage "1.1.3-SNAPSHOT"]
                  [refactor-nrepl "2.5.0-SNAPSHOT"]
                  [cider/cider-nrepl "0.23.0-SNAPSHOT"]
                  [cljfmt "0.6.4"]
                  [lein-cljfmt "0.6.4"]
                  [lein-bikeshed "0.5.2"]]
        :dependencies [[cider/piggieback "0.4.2"]
                       [slamhound "1.5.5"]
                       [com.bhauman/rebel-readline "0.1.4"]]
        :aliases {"slamhound" ["run" "-m" "slam.hound"]
                  "rebl" ["trampoline" "run" "-m" "rebel-readline.main"]}
                                        ; :repl-options {:nrepl-middleware [cider.piggieback/wrap-cljs-repl]}
        }}
