{:user {:plugins [[venantius/ultra "0.6.0"]
                  [lein-ancient "0.6.15"]
                  [lein-auto "0.1.3"]
                  [lein-kibit "0.1.6"]
                  [lein-nvd "1.1.1"]
                  [venantius/yagni "0.1.7"]
                  [lein-ancient "0.6.15"]
                  [jonase/eastwood "0.3.5"]
                  [lein-cloverage "1.0.13"]
                  [refactor-nrepl "2.4.0-SNAPSHOT"]
                  [cider/cider-nrepl "0.22.2"]
                  [venantius/yagni "0.1.7"]
                  [cljfmt "0.6.1"]
                  [lein-cljfmt "0.6.1"]
                  [lein-bikeshed "0.5.1"]]
        :dependencies [[cider/piggieback "0.4.0"]
                       [slamhound "1.5.5"]
                       [com.bhauman/rebel-readline "0.1.4"]]
        :aliases {"slamhound" ["run" "-m" "slam.hound"]
                  "rebl" ["trampoline" "run" "-m" "rebel-readline.main"]}
        ; :repl-options {:nrepl-middleware [cider.piggieback/wrap-cljs-repl]}
        }}
